name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

env:
  TZ: Asia/Shanghai 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S %Z"
        env:
          TZ: Asia/Shanghai
                    
      - name: system info
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h
          df -Th

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          wget -q -T 5 -t 3 -O- "${{ secrets.PREPARE_GEODATA }}" | bash
          wget -q -T 5 -t 3 -O- "${{ secrets.PREPARE_RULESET }}" | bash

      - name: prepare
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          git clone -b rules https://github.com/apoiston/index.git
          sed -i "s/N\/A/$(date +"%Y-%m-%d %H:%M:%S %Z")/g" index/index.html
          cp -a index/*.{html,css,js} $GITHUB_WORKSPACE

      - name: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan rules
          git rm -rf .
          git add *.{html,css,js} ruleset rules conf geox
          git commit -m "build: $(date +"%Y-%m-%d %H:%M:%S %Z")"
          git push -f origin rules
